### ISSUE TITLE
Refactor glue code to avoid requiring `-lcurl`

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s-curl#71]
Follow up to https://github.com/http4s/http4s-curl/pull/59#discussion_r1084826508. A user in #scala-native discord recently encountered this problem when trying to use http4s-curl. I was confused but lucky I remembered that comment and was able to suggest that they add that flag to fix their build.

Suffice to say, it's a bit unfortunate that this is necessary, since the `@link("curl")` is supposed to handle it.

If I understand correctly this is the code that introduced the problem.

https://github.com/http4s/http4s-curl/blob/5843751b3ce2c4da92ecf1c0e4380d1e3c73342c/curl/src/main/resources/scala-native/curl.c#L17-L23

I wonder if we could refactor that code, so instead of directly calling `curl_version_info` method, it takes the result of that method call and extracts the field from the struct. Then, we can call `curl_version_info()` directly from SN, and pass its result to that glue code helper. It's quite awkward on our end, but better for UX.

**Comment by hnaderi** [comment]
I tried to use the struct and extract it on scala side, but the problem was that `curl_version_info` struct is a huge struct with about 30 fields which some of them are nested, so it can't be implemented using `CStructN`, and also I have no idea if its size is constant or depends on the platform, so I decided to err on the side caution and implement it this way.

Do you know any similar example I can see?

**Comment by armanbilge** [comment]
I think destructuring the struct in C is the right approach. But you can call `curl_version_info()` from Scala to _get_ the struct, then pass it to a destructuring helper. e.g. see the glue code above
https://github.com/http4s/http4s-curl/blob/5843751b3ce2c4da92ecf1c0e4380d1e3c73342c/curl/src/main/resources/scala-native/curl.c#L5-L7
